name: Refresh jsDelivr Cache

on:
  push:
    branches:
      - main
    paths:
      - '*/manifest.json'

jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/manifest.json

      - name: Generate URL list
        id: generate-urls
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          URL_LIST=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            FULL_URL="https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/${file}"
            URL_LIST="${URL_LIST}${FULL_URL}"$'\n'
          done
          
          {
            echo "list<<EOF"
            echo "$URL_LIST"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Purge Cache
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            ${{ steps.generate-urls.outputs.list }}
